close all;
clear all;

% paths = getPaths('/home/ruiy/store/data/experiment/indoor-no-move/*/2019-05-16-14-13-43/calculated_csi.bin');
paths = getPaths('/home/ruiy/store/data/experiment/indoor-no-move-600/*/2019-04-01-10-23-16/calculated_csi.bin');

data = readData(paths);
data = abs(data);

normScale = 127;
L = 7;
delta = 4;

plotData = data;
for i = 1: size(data, 2)
    plotData(:, i) = data(:, i) * normScale / mean(data(:, i));
end

plotData = round(plotData);

plotData = plotData / pow2(delta);    

plot(plotData);

legend('alice', 'bob', 'eve');

grid on;

keyAlice = GenKey(data(:, 1));
keyBob = GenKey(data(:, 2));
keyEve = GenKey(data(:, 3));

xlim=get(gca,'xlim');
ylim=get(gca,'ylim');

fontSize = 12;
bitLen = 50;
text(50, sum(ylim) - 1, ['Key generated by alice: ' keyAlice(1:bitLen)], 'horiz', 'left', 'fontWeight', 'bold', 'fontSize', fontSize)
text(50, sum(ylim) - 2, ['Key generated by bob  : ' keyBob(1:bitLen)], 'horiz', 'left', 'fontWeight', 'bold', 'fontSize', fontSize)
text(50, sum(ylim) - 3, ['Key generated by eve  : ' keyEve(1:bitLen)], 'horiz', 'left', 'fontWeight', 'bold', 'fontSize', fontSize)