close all;
clear all;

% paths = getPaths('/home/ruiy/store/data/experiment/indoor-no-move/*/2019-05-16-14-13-43/calculated_csi.bin');
% paths = getPaths('/home/ruiy/store/data/experiment/corridor-long-distance-no-move/*/2019-05-14-13-23-50/calculated_csi.bin');
paths = getPaths('/home/ruiy/store/data/experiment/outdoor-no-move/*/2019-04-27-11-32-31/calculated_csi.bin')

data = readData(paths);
data = abs(data);

normScale = 127;
L = 7;
delta = 4;

plotData = data;
for i = 1: size(data, 2)
    plotData(:, i) = data(:, i) * normScale / mean(data(:, i));
end

plotData = round(plotData);

% plotData = floor(plotData / pow2(delta));    

maker_idx = 1:30:length(plotData);

% alice
p1 = plot(plotData(:, 1) / pow2(delta), 'b--o', 'MarkerIndices', maker_idx)
hold on
% q1 = plot(floor(plotData(:, 1) / pow2(delta)), 'b');

% bob
hold on
p2 = plot(plotData(:, 2) / pow2(delta), 'r--*', 'MarkerIndices', maker_idx) 
hold on
% q2 = plot(floor(plotData(:, 2) / pow2(delta)), 'r');

% eve
hold on
p3 = plot(plotData(:, 3) / pow2(delta), 'g--+', 'MarkerIndices', maker_idx)
hold on
% q3 = plot(floor(plotData(:, 3) / pow2(delta)), 'g');

% legend([p1 q1 p2 q2 p3 q3], "Alice's CSI", "Alice's Quantized CSI", "Bob's CSI", "Bob's Quantized CSI", "Eve's CSI", "Eve's Quantized CSI")

hold on

% plot(plotData / pow2(delta))

plot([0 600], [4 4], 'k-.');
plot([0 600], [8 8], 'k-.');
plot([0 600], [12 12], 'k-.');

grid on;
set(gca,'GridLineStyle',':','GridColor','k','GridAlpha',1);
set(gca, 'ytick', 0:1:16)
set(gca,'FontSize', 16)

legend([p1 p2 p3], "Alice的信道频率响应", "Bob的信道频率响应", "Eve的信道频率响应")

keyAlice = GenKey(data(:, 1));
keyBob = GenKey(data(:, 2));
keyEve = GenKey(data(:, 3));

xlim=get(gca,'xlim');
ylim=get(gca,'ylim');

fontSize = 12;
bitLen = 50;
N = 3;
text(250, sum(ylim) - 3, '将信道频率响应量化成4阶，然后转换成格雷码', 'horiz', 'left', 'fontWeight', 'bold', 'fontSize', fontSize)
text(220, sum(ylim) - N - 2, ['Key generated by Alice: ' keyAlice(1:bitLen)], 'horiz', 'left', 'fontWeight', 'bold', 'fontSize', fontSize)
text(220, sum(ylim) - N - 3, ['Key generated by Bob  : ' keyBob(1:bitLen)], 'horiz', 'left', 'fontWeight', 'bold', 'fontSize', fontSize)
text(220, sum(ylim) - N - 4, ['Key generated by Eve  : ' keyEve(1:bitLen)], 'horiz', 'left', 'fontWeight', 'bold', 'fontSize', fontSize)

xlabel('子载波序号')
ylabel('信道频率响应')

title('室外')